/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Intent = { 'investment' : null } |
  { 'living' : null };
export type Language = { 'spanish' : null } |
  { 'english' : null };
export interface Lead {
  'source' : Source,
  'name' : string,
  'email' : string,
  'language' : Language,
  'intent' : Intent,
  'timestamp' : Time,
  'phone' : string,
}
export type Source = { 'brochure' : null } |
  { 'whatsapp' : null } |
  { 'property' : null };
export type Time = bigint;
export interface _SERVICE {
  'captureLead' : ActorMethod<[Lead], undefined>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getBrochureDownloads' : ActorMethod<[string], bigint>,
  'getLeadsByIntent' : ActorMethod<[Intent], Array<Lead>>,
  'getLeadsBySource' : ActorMethod<[Source], Array<Lead>>,
  'getTotalLeads' : ActorMethod<[], bigint>,
  'recordBrochureDownload' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];