/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Source = IDL.Variant({
  'brochure' : IDL.Null,
  'whatsapp' : IDL.Null,
  'property' : IDL.Null,
});
export const Language = IDL.Variant({
  'spanish' : IDL.Null,
  'english' : IDL.Null,
});
export const Intent = IDL.Variant({
  'investment' : IDL.Null,
  'living' : IDL.Null,
});
export const Time = IDL.Int;
export const Lead = IDL.Record({
  'source' : Source,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'language' : Language,
  'intent' : Intent,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'captureLead' : IDL.Func([Lead], [], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getBrochureDownloads' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getLeadsByIntent' : IDL.Func([Intent], [IDL.Vec(Lead)], ['query']),
  'getLeadsBySource' : IDL.Func([Source], [IDL.Vec(Lead)], ['query']),
  'getTotalLeads' : IDL.Func([], [IDL.Nat], ['query']),
  'recordBrochureDownload' : IDL.Func([IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Source = IDL.Variant({
    'brochure' : IDL.Null,
    'whatsapp' : IDL.Null,
    'property' : IDL.Null,
  });
  const Language = IDL.Variant({ 'spanish' : IDL.Null, 'english' : IDL.Null });
  const Intent = IDL.Variant({ 'investment' : IDL.Null, 'living' : IDL.Null });
  const Time = IDL.Int;
  const Lead = IDL.Record({
    'source' : Source,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'language' : Language,
    'intent' : Intent,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'captureLead' : IDL.Func([Lead], [], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getBrochureDownloads' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getLeadsByIntent' : IDL.Func([Intent], [IDL.Vec(Lead)], ['query']),
    'getLeadsBySource' : IDL.Func([Source], [IDL.Vec(Lead)], ['query']),
    'getTotalLeads' : IDL.Func([], [IDL.Nat], ['query']),
    'recordBrochureDownload' : IDL.Func([IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };