/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Lead {
    source: Source;
    name: string;
    email: string;
    language: Language;
    intent: Intent;
    timestamp: Time;
    phone: string;
}
export type Time = bigint;
export enum Intent {
    investment = "investment",
    living = "living"
}
export enum Language {
    spanish = "spanish",
    english = "english"
}
export enum Source {
    brochure = "brochure",
    whatsapp = "whatsapp",
    property = "property"
}
export interface backendInterface {
    captureLead(lead: Lead): Promise<void>;
    getAllLeads(): Promise<Array<Lead>>;
    getBrochureDownloads(email: string): Promise<bigint>;
    getLeadsByIntent(intent: Intent): Promise<Array<Lead>>;
    getLeadsBySource(source: Source): Promise<Array<Lead>>;
    getTotalLeads(): Promise<bigint>;
    recordBrochureDownload(email: string): Promise<bigint>;
}
import type { Intent as _Intent, Language as _Language, Lead as _Lead, Source as _Source, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async captureLead(arg0: Lead): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.captureLead(to_candid_Lead_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.captureLead(to_candid_Lead_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBrochureDownloads(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrochureDownloads(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrochureDownloads(arg0);
            return result;
        }
    }
    async getLeadsByIntent(arg0: Intent): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByIntent(to_candid_Intent_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByIntent(to_candid_Intent_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsBySource(arg0: Source): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsBySource(to_candid_Source_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsBySource(to_candid_Source_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalLeads(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalLeads();
            return result;
        }
    }
    async recordBrochureDownload(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBrochureDownload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBrochureDownload(arg0);
            return result;
        }
    }
}
function from_candid_Intent_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Intent): Intent {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Source_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Source): Source {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: _Source;
    name: string;
    email: string;
    language: _Language;
    intent: _Intent;
    timestamp: _Time;
    phone: string;
}): {
    source: Source;
    name: string;
    email: string;
    language: Language;
    intent: Intent;
    timestamp: Time;
    phone: string;
} {
    return {
        source: from_candid_Source_n12(_uploadFile, _downloadFile, value.source),
        name: value.name,
        email: value.email,
        language: from_candid_Language_n14(_uploadFile, _downloadFile, value.language),
        intent: from_candid_Intent_n16(_uploadFile, _downloadFile, value.intent),
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    brochure: null;
} | {
    whatsapp: null;
} | {
    property: null;
}): Source {
    return "brochure" in value ? Source.brochure : "whatsapp" in value ? Source.whatsapp : "property" in value ? Source.property : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spanish: null;
} | {
    english: null;
}): Language {
    return "spanish" in value ? Language.spanish : "english" in value ? Language.english : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    investment: null;
} | {
    living: null;
}): Intent {
    return "investment" in value ? Intent.investment : "living" in value ? Intent.living : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Intent_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Intent): _Intent {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Lead_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lead): _Lead {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Source_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Source): _Source {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    source: Source;
    name: string;
    email: string;
    language: Language;
    intent: Intent;
    timestamp: Time;
    phone: string;
}): {
    source: _Source;
    name: string;
    email: string;
    language: _Language;
    intent: _Intent;
    timestamp: _Time;
    phone: string;
} {
    return {
        source: to_candid_Source_n3(_uploadFile, _downloadFile, value.source),
        name: value.name,
        email: value.email,
        language: to_candid_Language_n5(_uploadFile, _downloadFile, value.language),
        intent: to_candid_Intent_n7(_uploadFile, _downloadFile, value.intent),
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Source): {
    brochure: null;
} | {
    whatsapp: null;
} | {
    property: null;
} {
    return value == Source.brochure ? {
        brochure: null
    } : value == Source.whatsapp ? {
        whatsapp: null
    } : value == Source.property ? {
        property: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    spanish: null;
} | {
    english: null;
} {
    return value == Language.spanish ? {
        spanish: null
    } : value == Language.english ? {
        english: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Intent): {
    investment: null;
} | {
    living: null;
} {
    return value == Intent.investment ? {
        investment: null
    } : value == Intent.living ? {
        living: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
